version = 0.1
[default.deploy.parameters]
stack_name = "user-orders"
resolve_s3 = true
s3_prefix = "user-orders"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "UserPool=\"us-east-1_syayYKIjn\""
image_repositories = []
